<a href="https://www.kaggle.com/code/kapturovalexander/kapturov-s-loan-approval-prediction-s4e10?scriptVersionId=198987249" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

# <span style="background-image: url(https://www.kaggle.com/competitions/84894/images/header); color: gold; font-size: 50px; padding: 10px;">Loan Approval Prediction</span>
## <span style="border: solid gold 3px; background-color: #B58050; color: white; padding: 3px">Playground Series - Season 4, Episode 10

In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/playground-series-s4e10/sample_submission.csv
/kaggle/input/playground-series-s4e10/train.csv
/kaggle/input/playground-series-s4e10/test.csv

#### - <span style="color: #B58050">version 1</span> (first glance at the data, without EDA)

![](https://www.kaggle.com/competitions/84894/images/header)

## ðŸª™ <span style="color: #B58050">Starting from this competition I will return to daily activity on kaggle because I need to become a strong professional in machine learning and data science. I hope this notebook will be the best among my previous ones and my results at the end of the competition will be good!

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
# 'id' feature is index
train = pd.read_csv('/kaggle/input/playground-series-s4e10/train.csv', index_col=0)
test = pd.read_csv('/kaggle/input/playground-series-s4e10/test.csv', index_col=0)

In [4]:
# Display all features in DataFrame
pd.set_option('display.max_columns', None)

In [5]:
train.head()

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length,loan_status
id,,,,,,,,,,,,
0,37,35000,RENT,0.0,EDUCATION,B,6000,11.49,0.17,N,14,0
1,22,56000,OWN,6.0,MEDICAL,C,4000,13.35,0.07,N,2,0
2,29,28800,OWN,8.0,PERSONAL,A,6000,8.90,0.21,N,10,0
3,30,70000,RENT,14.0,VENTURE,B,12000,11.11,0.17,N,5,0
4,22,60000,RENT,2.0,MEDICAL,A,6000,6.92,0.10,N,3,0

In [6]:
train.tail(3)

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length,loan_status
id,,,,,,,,,,,,
58642,23,44000,RENT,7.0,EDUCATION,D,6800,16.00,0.15,N,2,1
58643,22,30000,RENT,2.0,EDUCATION,A,5000,8.90,0.17,N,3,0
58644,31,75000,MORTGAGE,2.0,VENTURE,B,15000,11.11,0.20,N,5,0

- #### <span style="color: #B58050">**person_age**</span>: Age of the person applying for the loan, measured in years.
- #### <span style="color: #B58050">**person_income**</span>: Annual income of the applicant in dollars.
- #### <span style="color: #B58050">**person_home_ownership**</span>: Type of home ownership (e.g., RENT, MORTGAGE, OWN).
- #### <span style="color: #B58050">**person_emp_length**</span> Length of employment in years at the current job.
- #### <span style="color: #B58050">**loan_intent**</span>: Purpose of the loan (e.g., EDUCATION, VENTURE, PERSONAL).
- #### <span style="color: #B58050">**loan_grade**</span>: Assigned grade to the loan indicating its risk profile (e.g., A is the best, D is riskier).
- #### <span style="color: #B58050">**loan_amnt**</span>: Amount of money requested by the applicant for the loan.
- #### <span style="color: #B58050">**loan_int_rate**</span>: Annual interest rate of the loan, shown as a percentage.
- #### <span style="color: #B58050">**loan_percent_income**</span>: Ratio of the loan amount to the applicant's annual income.
- #### <span style="color: #B58050">**cb_person_default_on_file**</span>: Indicator of whether the person has a history of defaulting on other credit obligations (Y for Yes, N for No).
- #### <span style="color: #B58050">**cb_person_cred_hist_length**</span>: Length of the applicant's credit history, measured in years.
- #### <span style="color: #B58050">**loan_status**</span>: Status of the loan (1 if defaulted, 0 if not).

In [7]:
# For visualization purposes
numeric = ['person_age', 'person_income', 'person_emp_length', 'loat_amnt', 'loan_int_rate', 'loan_percent_income', 'cb_person_cred_hist_length']
categorical = ['person_home_ownership', 'loan_intent', 'loan_grade', 'cb_person_default_on_file']

In [8]:
train.shape

(58645, 12)

### <span style="color: #B58050">There are 12 features (one of them is target) and about 59K observations

In [9]:
test.shape

(39098, 11)

![](https://images.ctfassets.net/1aemqu6a6t65/5rPsNLkgpwvZPSmjhE5ChB/9ee0978b3d792515d59fefab5296b832/wall-street-photo-tagger-yancey-iv-nyc-and-company-02-2?w=1200&h=800&q=75)

In [10]:
train.info()

<class 'pandas.core.frame.DataFrame'>
Index: 58645 entries, 0 to 58644
Data columns (total 12 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   person_age                  58645 non-null  int64
 1   person_income               58645 non-null  int64
 2   person_home_ownership       58645 non-null  object
 3   person_emp_length           58645 non-null  float64
 4   loan_intent                 58645 non-null  object
 5   loan_grade                  58645 non-null  object
 6   loan_amnt                   58645 non-null  int64
 7   loan_int_rate               58645 non-null  float64
 8   loan_percent_income         58645 non-null  float64
 9   cb_person_default_on_file   58645 non-null  object
 10  cb_person_cred_hist_length  58645 non-null  int64
 11  loan_status                 58645 non-null  int64
dtypes: float64(3), int64(5), object(4)
memory usage: 5.8+ MB

### <span style="color: #B58050">At first glance, there are no gaps in the data.

In [11]:
train.describe().T

,count,mean,std,min,25%,50%,75%,max
person_age,58645.0,27.550857,6.033216,20.00,23.00,26.00,30.00,123.00
person_income,58645.0,64046.172871,37931.106978,4200.00,42000.00,58000.00,75600.00,1900000.00
person_emp_length,58645.0,4.701015,3.959784,0.00,2.00,4.00,7.00,123.00
loan_amnt,58645.0,9217.556518,5563.807384,500.00,5000.00,8000.00,12000.00,35000.00
loan_int_rate,58645.0,10.677874,3.034697,5.42,7.88,10.75,12.99,23.22
loan_percent_income,58645.0,0.159238,0.091692,0.00,0.09,0.14,0.21,0.83
cb_person_cred_hist_length,58645.0,5.813556,4.029196,2.00,3.00,4.00,8.00,30.00
loan_status,58645.0,0.142382,0.349445,0.00,0.00,0.00,0.00,1.00

In [12]:
train.describe(include=['object']).T

                           count unique        top   freq
person_home_ownership      58645      4       RENT  30594
loan_intent                58645      6  EDUCATION  12271
loan_grade                 58645      7          A  20984
cb_person_default_on_file  58645      2          N  49943